Linear transformations

In [1]:
import numpy as np
matrix=np.array([[2,0],[0,3]])

vector=np.array([1,2])
print("Original Vector:- ",vector)
vector_transformed=matrix @ vector
print("Transformed vector:- ",vector_transformed)

Original Vector:-  [1 2]
Transformed vector:-  [2 6]


Determinants in 2D and 3D transformations

In [2]:
det_2d=np.linalg.det(matrix)
print("Detreminants of above 2d Matrix:- ",det_2d)

matrix_3d=np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(matrix_3d)
print(matrix_3d.ndim)

det_3d=np.linalg.det(matrix_3d)
print("Determiants of above 3d Matrix:- ",det_3d)

Detreminants of above 2d Matrix:-  6.0
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
Determiants of above 3d Matrix:-  -9.51619735392994e-16
