In [1]:
import numpy as np

Tensors are nothing but a data structure which just store the numbers, It is like a common name for making all dimension
Scalar,Vectors,Matrices,multi-dimensional matrices are all part of Tensors, It is mostly used when we have to represent and do anything on large datasets, images, videos, etc..

0D Tensors or Scalars

In [2]:
a=np.array(4)
print(a)
print("Dimension of a: ",a.ndim)

4
Dimension of a:  0


1D Tensors or Vectors

In [3]:
a=np.array([1,2,3,4,5])
print(a)
print("Dimension of a: ",a.ndim)

[1 2 3 4 5]
Dimension of a:  1


2D Tensors or Matrices

In [4]:
a=np.array([[1,2],[3,4]])
print(a)
print("Dimension(or Rank or Axis) of a: ",a.ndim)

[[1 2]
 [3 4]]
Dimension(or Rank or Axis) of a:  2


ND Tensors> 

In [5]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)
print("Dimension of arr3: ",arr3.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimension of arr3:  3


In [6]:
arr4=np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]]]])
print(arr4)
print("Dimension of arr4: ",arr4.ndim)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]]
Dimension of arr4:  4


In [7]:
arr5=np.array([[[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]]]],[[[[25,26,27],[28,29,30]],[[31,32,33],[34,35,36]]],[[[37,38,39],[40,41,42]],[[43,44,45],[46,47,48]]]]])
print(arr5)
print("Dimension of arr5: ",arr5.ndim)

[[[[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [10 11 12]]]


  [[[13 14 15]
    [16 17 18]]

   [[19 20 21]
    [22 23 24]]]]



 [[[[25 26 27]
    [28 29 30]]

   [[31 32 33]
    [34 35 36]]]


  [[[37 38 39]
    [40 41 42]]

   [[43 44 45]
    [46 47 48]]]]]
Dimension of arr5:  5


In [8]:
print(a)
print(a.shape)
print(a.size)
print(np.linalg.norm(a))

[[1 2]
 [3 4]]
(2, 2)
4
5.477225575051661
